# Site settings
baseurl = "https://kczenczek.github.io/Python-w-Malinach/"
publishDir = "docs"
themesDir = "themes"
languageCode = "en-us"
title = "Python w Malinach"
theme = "cactus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[params]
	name = "Kinga"
	description = "This is a blog about RPi projects"
	bio = "Bonbon cake donut. I love jelly-o jelly I love lollipop. Chupa chups cotton candy I love icing pie sweet muffin I love."
	# Enter optionally your twitter account
	twitter = "Your Twitter account"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []


	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = "Powered by [Hugo](//gohugo.io). Theme by [Cactus](https://github.com/digitalcraftsman/hugo-cactus-theme)."
	# Sharing options and author information in posts
	aboutAuthor = "I'm a Python-padawan."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    #twitter  = "https://www.twitter.com/"
    facebook = "https://www.facebook.com/"
    github   = "https://www.github.com/"
    #dribble  = "https://www.dribbble.com/"
